apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-operator
  labels:
    app.kubernetes.io/name: unifi-operator
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unifi-operator
    spec:
      containers:
        - name: unifi-operator
          image: ghcr.io/craigcabrey/unifi-operator:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: unifi-operator
