apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-unifi-controller
  labels:
    app.kubernetes.io/name: k8s-unifi-controller
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-unifi-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-unifi-controller
    spec:
      serviceAccountName: k8s-unifi-controller
      containers:
        - name: k8s-unifi-controller
          image: ghcr.io/craigcabrey/k8s-unifi-controller:latest
          imagePullPolicy: Always
          args:
            - --unifi-insecure
            - --watch
          envFrom:
            - secretRef:
                name: k8s-unifi-controller
