apiVersion: v1
kind: ServiceAccount
metadata:
  name: unifi-operator
  labels:
    app.kubernetes.io/name: unifi-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unifi-operator
  labels:
    app.kubernetes.io/name: unifi-operator
rules:
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unifi-operator
  labels:
    app.kubernetes.io/name: unifi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unifi-operator
subjects:
  - kind: ServiceAccount
    name: unifi-operator
    namespace: default
