apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-unifi-controller
  labels:
    app.kubernetes.io/name: k8s-unifi-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-unifi-controller
  labels:
    app.kubernetes.io/name: k8s-unifi-controller
rules:
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-unifi-controller
  labels:
    app.kubernetes.io/name: k8s-unifi-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-unifi-controller
subjects:
  - kind: ServiceAccount
    name: k8s-unifi-controller
    namespace: default
